name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
    
      - uses: ko-build/setup-ko@v0.6

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push
        run: |
          build_tag="${{ github.ref_name }}"
          KO_DOCKER_REPO=ghcr.io/ozansz/otelapp ko build --platform all --tags "latest,$build_tag" -B cmd/otelapp

